DELETE {
  graph <http://isi.edu/ckg/g/wd> {
  	%root% %dateModified% ?o .
  }
}
WHERE {
  graph <http://isi.edu/ckg/g/wd> {
  	%root% %dateModified% ?o .
  }
};
INSERT DATA {
  graph <http://isi.edu/ckg/g/wd> {
  	%root% %dateModified% %date% .
  }
}
