SELECT DISTINCT ?entity ?s
WHERE {
  graph <http://isi.edu/ckg/g/wd> {
	  VALUES ?entity {
	     %entityList%
	  }
	  ?entity ?statementPred ?statement .
	  FILTER( STRSTARTS(STR(?statement), "%uris.statement%") ) .
	  ?statement %prov:wasDerivedFrom% ?s .
	  FILTER EXISTS { ?s ?p [] }
  }
}
