SELECT DISTINCT ?s WHERE {
  graph <http://isi.edu/ckg/g/wd> {
	  VALUES (?s ?rev) {
	    %values%
	  }
	  OPTIONAL {
	     ?s %schema:version% ?repoRev
	  }
	  FILTER (!bound(?repoRev) || ?repoRev < ?rev)
  }
}
